/***********************************************************************************************
 * @(#)Country.java
 *
 * Version: 1.0
 *
 * Date: 2014/09/09
 *
 * Copyright (c) 2014 Thiago Alexandre Martins Monteiro.
 *
 * All rights reserved. This program and the accompanying materials are made 
 * available under the terms of the GNU Public License v2.0 which accompanies 
 * this distribution, and is available at http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * Contributors:
 *    Thiago Alexandre Martins Monteiro - initial API and implementation
 ************************************************************************************************/

package app.models;

import jedi.db.models.CharField;
import jedi.db.models.Manager;
import jedi.db.models.Model;
import jedi.db.models.QuerySet;
import jedi.db.models.Table;

/**
 * <h2>Classe que modela um país.</h2>
 * <h3>Código:</h3>
 * <pre>
 * <code class="java">
 * package app.models;
 *
 * import jedi.db.models.CharField;
 * import jedi.db.models.Manager;
 * import jedi.db.models.Model;
 * import jedi.db.models.QuerySet;
 * import jedi.db.models.Table;
 *
 *{@literal @}Table(name="countries", engine="InnoDB", charset="utf8", comment="Table of countries.")
 * public class Country extends Model {
 *
 *     // Attributes
 *     private static final long serialVersionUID = 8197600275231031642L;
 *
 *    {@literal @}CharField(max_length = 50, unique = true, comment = "Country\\'s Name")
 *     private String name;
 *
 *    {@literal @}CharField(max_length = 2, unique = true)
 *     private String acronym;
 *
 *    {@literal @}CharField(
 *         max_length = 1, 
 *         required = false, 
 *         default_value = "A", 
 *         comment = "Country\\'s Status (A - Active / I - Inactive)"
 *     )
 *     private String status;
 *
 *     public static Manager objects = new Manager(Country.class);
 *
 *     // Constructors
 *     public Country() {}
 *
 *     public Country(String name, String acronym) {
 *         this.name = name;
 *         this.acronym = acronym;
 *     }
 *
 *     public Country(String name, String acronym, String status) {
 *         this(name, acronym);
 *         this.status = status;
 *     }
 *
 *     // Getters
 *     public String getName() {
 *         return name;
 *     }
 *
 *     public String getAcronym() {
 *         return acronym;
 *     }
 *
 *     public String getStatus() {
 *         return status;
 *     }
 *
 *     // Setters
 *     public void setName(String name) {
 *         this.name = name;
 *     }
 *
 *     public void setAcronym(String acronym) {
 *         this.acronym = acronym;
 *     }
 *
 *     public void setStatus(String status) {
 *         this.status = status;
 *     }
 *
 *     // Generated by Jedi ORM
 *     public QuerySet<State> getStateSet() {
 *         return State.objects.getSet(Country.class, this.id);
 *     }
 * }
 * </code>
 * </pre>
 *
 * @author Thiago Monteiro
 * @version 1.0
 * @since 1.0
 *
 * @see java.lang.Long
 * @see java.lang.String
 *
 * @see jedi.db.models.CharField
 * @see jedi.db.models.Manager
 * @see jedi.db.models.Model
 * @see jedi.db.models.QuerySet
 * @see jedi.db.models.Table
 *
 * @see app.models.State
 */
@Table(name="countries", engine="InnoDB", charset="utf8", comment="Table of countries.")
public class Country extends Model {

    // Attributes

    /**
     * Número de versão da classe.
     *
     * @see java.lang.Long
     */
    private static final long serialVersionUID = 8197600275231031642L;

    /**
     * Nome do país.
     *
     * @see java.lang.String
     *
     * @see jedi.db.models.CharField
     */
    @CharField(max_length = 50, unique = true, comment = "Country\\'s Name")
    private String name;

    /**
     * Sigla do país.
     *
     * @see java.lang.String
     *
     * @see jedi.db.models.CharField
     */
    @CharField(max_length = 2, unique = true)
    private String acronym;

    /**
     * Status do registro do país (ativo / inativo).
     *
     * @see java.lang.String
     *
     * @see jedi.db.models.CharField
     */
    @CharField(
        max_length = 1, 
        required = false, 
        default_value = "A", 
        comment = "Country\\'s Status (A - Active / I - Inactive)"
    )
    private String status;

    /**
     * Gerenciador de consultas a objetos dessa classe persistidos em banco de dados.
     *
     * @see jedi.db.models.Manager
     *
     * @see app.models.Country
     */
    public static Manager objects = new Manager(Country.class);

    // Constructors

    /**
     * Construtor padrão.
     */
    public Country() {}

    /**
     * Construtor que recebe o nome e a sigla do país.
     *
     * @param name o nome do país
     * @param acronym a sigla do país
     *
     * @see java.lang.String
     */
    public Country(String name, String acronym) {
        this.name = name;
        this.acronym = acronym;
    }

    /**
     * Construtor que recebe o nome, a sigla e o 
     * status cadastral do país.
     *
     * @param name o nome do país
     * @param acronym a sigla do país
     * @param status o status cadastral do país (ativo / inativo)
     *
     * @see java.lang.String
     */
    public Country(String name, String acronym, String status) {
        this(name, acronym);
        this.status = status;
    }

    // Getters

    /**
     * Retorna o nome do país.
     *
     * @return o nome do país
     *
     * @see java.lang.String
     */
    public String getName() {
        return name;
    }

    /**
     * Retorna a sigla do país.
     *
     * @return a sigla do país
     *
     * @see java.lang.String
     */
    public String getAcronym() {
        return acronym;
    }

    /**
     * Retorna o status cadastral do país.
     *
     * @return o status cadastral do país (ativo / inativo)
     *
     * @see java.lang.String
     */
    public String getStatus() {
        return status;
    }

    // Setters

    /**
     * Define o nome do país.
     *
     * @param name nome do país
     *
     * @see java.lang.String
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Define a sigla do país.
     *
     * @param acronym sigla do país
     *
     * @see java.lang.String
     */
    public void setAcronym(String acronym) {
        this.acronym = acronym;
    }

    /**
     * Define o status cadastral do país.
     *
     * @param status status cadastral do país (ativo / inativo)
     *
     * @see java.lang.String
     */
    public void setStatus(String status) {
        this.status = status;
    }

    // Generated by Jedi ORM
    /**
     * Retorna o conjunto de estados associados ao país.
     *
     * @return estados associados ao país
     *
     * @see jedi.db.models.QuerySet
     *
     * @see app.models.State
     */
    public QuerySet<State> getStateSet() {
        return State.objects.getSet(Country.class, this.id);
    }
}
